from pydantic import BaseModel, Field
from typing import List, Optional

class TelemetryRequest(BaseModel):
    """Pydantic model representing incoming zone telemetry with physical sensor limits."""
    zone: str = Field(..., description="Refinery zone name (e.g. Zone A, Zone B, Zone C)", min_length=1)
    temperature: float = Field(..., ge=0.0, le=100.0, description="Temperature in °C (0 to 100)")
    gas_level: float = Field(..., ge=0.0, le=100.0, description="Gas concentration level in % LEL (0 to 100)")
    pressure: float = Field(..., ge=0.0, le=100.0, description="Process pressure percentage (0 to 100)")
    ventilation: float = Field(..., ge=0.0, le=100.0, description="Ventilation capacity percentage (0 to 100)")
    maintenance_activity: bool = Field(..., description="Maintenance activity status permit")
    hot_work_permit: bool = Field(..., description="Hot work permit status")
    confined_space_entry: bool = Field(..., description="Confined space entry permit status")

class AnalysisResponse(BaseModel):
    """Calculated risk + original telemetry."""

    zone: str

    # Raw telemetry
    temperature: float
    gas_level: float
    pressure: float
    ventilation: float

    maintenance_activity: bool
    hot_work_permit: bool
    confined_space_entry: bool

    # Risk engine output
    incident_type: str
    risk_score: float
    confidence_score: int
    time_to_escalation: str
    risk_factors: List[str]
    recommended_actions: List[str]

class DashboardResponse(BaseModel):

    overall_risk: str

    overall_score: float

    average_risk: float

    critical_zone: Optional[str]

    high_risk_zones: int

    zone_count: int

    last_updated: str

    summary: str

    zones: List[AnalysisResponse]

class ExplainRequest(BaseModel):
    zone: str

    # Raw telemetry
    temperature: float
    gas_level: float
    pressure: float
    ventilation: float

    maintenance_activity: bool
    hot_work_permit: bool
    confined_space_entry: bool

    # Risk analysis
    incident_type: str
    risk_score: float
    confidence_score: Optional[int] = None
    confidence: Optional[int] = None
    time_to_escalation: str

    risk_factors: List[str] = Field(default_factory=list)
    recommended_actions: List[str] = Field(default_factory=list)

    def get_confidence(self):
        return self.confidence_score or self.confidence or 75

class ExplainResponse(BaseModel):
    """Structured industrial safety report generated by Gemini AI."""
    executive_summary: str = Field(..., description="High-level executive summary of the safety risk")
    root_causes: List[str] = Field(..., description="Identified root causes and contributing factors")
    possible_consequences: List[str] = Field(..., description="Potential consequences if unmitigated")
    immediate_actions: List[str] = Field(..., description="Immediate mitigation steps required")
    long_term_prevention: List[str] = Field(..., description="Long-term prevention measures")
    priority: str = Field(..., description="Safety action priority level (CRITICAL, HIGH, MEDIUM, LOW)")